spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: xxx
            client-secret: xxx

app:
  safe-zone:
    secret: "123"  # Secret for the safe zone header

logging:
  level:
    org.springframework.security: TRACE
